---
- name: Converge
  become: false
  connection: local
  gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: Printenv
      ansible.builtin.command: printenv
      changed_when: false

    - name: Pwd
      ansible.builtin.command: pwd
      changed_when: false

    - name: Install apt role
      community.general.ansible_galaxy_install:
        type: role
        name: chriscroome.apt

    - name: Include Role
      ansible.builtin.include_role:
        name: openproject
...
