---
- name: Converge
  become: false
  connection: local
  gather_facts: false
  hosts:
    - localhost
  tasks:

    - name: Include Role
      ansible.builtin.include_role:
        name: openproject
...
